// Generated by gencpp from file carla_msgs/CarlaRadarMeasurement.msg
// DO NOT EDIT!


#ifndef CARLA_MSGS_MESSAGE_CARLARADARMEASUREMENT_H
#define CARLA_MSGS_MESSAGE_CARLARADARMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <carla_msgs/CarlaRadarDetection.h>

namespace carla_msgs
{
template <class ContainerAllocator>
struct CarlaRadarMeasurement_
{
  typedef CarlaRadarMeasurement_<ContainerAllocator> Type;

  CarlaRadarMeasurement_()
    : header()
    , detections()  {
    }
  CarlaRadarMeasurement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::carla_msgs::CarlaRadarDetection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::carla_msgs::CarlaRadarDetection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct CarlaRadarMeasurement_

typedef ::carla_msgs::CarlaRadarMeasurement_<std::allocator<void> > CarlaRadarMeasurement;

typedef boost::shared_ptr< ::carla_msgs::CarlaRadarMeasurement > CarlaRadarMeasurementPtr;
typedef boost::shared_ptr< ::carla_msgs::CarlaRadarMeasurement const> CarlaRadarMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator1> & lhs, const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator1> & lhs, const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ea43324c6693f5d104fc272e6fdd08e";
  }

  static const char* value(const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ea43324c6693f5dULL;
  static const uint64_t static_value2 = 0x104fc272e6fdd08eULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_msgs/CarlaRadarMeasurement";
  }

  static const char* value(const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2020 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"\n"
"Header header\n"
"\n"
"CarlaRadarDetection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: carla_msgs/CarlaRadarDetection\n"
"#\n"
"# Copyright (c) 2020 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"\n"
"float32 altitude\n"
"float32 azimuth\n"
"float32 depth\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarlaRadarMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_msgs::CarlaRadarMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::carla_msgs::CarlaRadarDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_MSGS_MESSAGE_CARLARADARMEASUREMENT_H
